name: CI

on:
  push:
    branches: [main]
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
     
     - name: Checkout
       uses: actions/checkout@v4.2.1
    
     - name: Docker Login
       uses: docker/login-action@v3.3.0
       with: 
         username: ${{ secrets.USER_DOCKER }}
         password: ${{ secrets.PASSWD_DOCKER }}

     - name: Build and push Docker images
       uses: docker/build-push-action@v6.9.0
       with: 
        context: .
        push: true
        tags: | 
          jsambarreto/iabotifbadev:v1
          jsambarreto/iabotifbadev:latest
